import streamlit as st
import requests
import re
import pandas as pd
from urllib.parse import urlparse

# 1. Put your list of exact URLs here:
COMMUNITY_COLLEGE_URLS = [
    "https://www.atc.edu/",
    "www.alamancecc.edu/",
    "www.albanytech.edu/",
    "www.alextech.edu/",
    "www.hancockcollege.edu/",
    "www.allegany.edu/",
    "https://www.allencc.edu/",
    "www.alvincollege.edu/",
    "www.actx.edu/",
    "https://www.arc.losrios.edu/",
    "www.angelina.edu/",
    "www.aacc.edu/",
    "www.anokatech.edu/",
    "www.anokaramsey.edu/",
    "https://www.azwestern.edu/",
    "www.anc.edu/",
    "www.asumidsouth.edu/",
    "www.asutr.edu/",
    "www.asub.edu/",
    "www.asumh.edu/",
    "https://www.asun.edu/",
    "www.abtech.edu/",
    "https://ashland.kctcs.edu/",
    "www.asnuntuck.edu/",
    "www.athenstech.edu/",
    "https://atlantatech.edu/",
    "atlanticcape.edu/",
    "www.atlantictechnicalcollege.edu/",
    "www.augustatech.edu/",
    "autrytech.edu/",
    "www.bccc.edu/",
    "www.barstow.edu/",
    "https://www.bartonccc.edu/",
    "https://www.batestech.edu/",
    "www.mybrcc.edu/",
    "https://www.baycollege.edu/",
    "www.beaufortccc.edu/",
    "www.belmontcollege.edu/",
    "https://www.bergen.edu/",
    "www.berkeleycitycollege.edu/",
    "www.berkshirecc.edu/",
    "www.bscc.edu/",
    "https://bigsandy.kctcs.edu/",
    "www.bishop.edu/",
    "www.bhc.edu/",
    "www.blackrivertech.edu/",
    "www.blackhawk.edu/",
    "https://www.bladencc.edu/",
    "www.blinn.edu/",
    "https://www.bluecc.edu/",
    "https://www.blueridgectc.edu/",
    "https://www.brcc.edu/",
    "www.blueridge.edu/",
    "https://bluegrass.kctcs.edu/",
    "https://www.gobctc.com/",
    "https://www.bpcc.edu/",
    "www.bridgevalley.edu/",
    "https://www.brightpoint.edu/",
    "www.bristolcc.edu/",
    "https://www.brookdalecc.edu/",
    "www.brunswickcc.edu/",
    "www.bucks.edu/",
    "www.bhcc.edu/",
    "www.butlercc.edu/",
    "https://www.bc3.edu/",
    "www.butte.edu/",
    "https://www.cabrillo.edu/",
    "https://www.cccti.edu/",
    "https://cincollege.org/",
    "https://www.camdencc.edu/",
    "canadacollege.edu/",
    "www.cvtech.edu/",
    "www.littlehoop.edu/",
    "www.capecod.edu/",
    "www.cfcc.edu/",
    "www.capectc.org/",
    "https://www.carlalbert.edu/",
    "www.sandburg.edu/",
    "https://www.carrollcc.edu/",
    "www.carteret.edu/",
    "www.carvercareercenter.edu/",
    "https://www.caspercollege.edu/",
    "www.cvcc.edu/",
    "https://www.cayuga-cc.edu/",
    "www.cecil.edu/",
    "www.cacc.edu/",
    "www.centralaz.edu/",
    "www.cccc.edu/",
    "www.cctech.edu/",
    "https://www.cccneb.edu/",
    "www.centralgatech.edu/",
    "www.clcmn.edu/",
    "www.cltcc.edu/",
    "https://www.cmcc.edu/",
    "https://www.cnm.edu/",
    "www.cocc.edu/",
    "www.cpi.edu/",
    "www.cpcc.edu/",
    "https://www.ctcd.edu/",
    "www.centralvirginia.edu/",
    "https://www.century.edu/",
    "www.cerritos.edu/",
    "https://cerrocoso.edu/",
    "www.chabotcollege.edu/",
    "https://www.chaffey.edu/",
    "www.cgc.maricopa.edu/",
    "www.chattahoocheetech.edu/",
    "https://www.cv.edu/",
    "https://www.chattanoogastate.edu/",
    "https://www.chesapeake.edu/",
    "cdkc.edu/",
    "www.cvtc.edu/",
    "https://www.cisco.edu/",
    "https://www.citruscollege.edu/",
    "www.ccsf.edu/",
    "www.ccc.edu/colleges/washington/Pages/default.aspx",
    "www.ccc.edu/colleges/truman/Pages/default.aspx",
    "www.ccc.edu/colleges/kennedy/pages/default.aspx",
    "www.ccc.edu/colleges/malcolm-x/pages/default.aspx",
    "www.ccc.edu/colleges/olive-harvey/Pages/default.aspx",
    "ccc.edu/colleges/daley/pages/default.aspx",
    "ccc.edu/colleges/wright/pages/default.aspx",
    "www.clackamas.edu/",
    "www.clarendoncollege.edu/",
    "www.clatsopcc.edu/",
    "www.clevelandcc.edu/",
    "www.clevelandstatecc.edu/",
    "https://www.clinton.edu/",
    "https://www.cloud.edu/",
    "www.clovis.edu/",
    "www.cloviscollege.edu/",
    "www.coahomacc.edu/",
    "https://www.westhillscollege.com/coalinga/",
    "www.coastalalabama.edu/",
    "www.coastalbend.edu/",
    "www.coastalcarolina.edu/",
    "www.coastalpines.edu/",
    "www.coastline.edu/",
    "https://www.cochise.edu/",
    "www.coconino.edu/",
    "www.coffeyville.edu/",
    "www.colbycc.edu/",
    "https://alameda.edu/",
    "www.cod.edu/",
    "www.cei.edu/",
    "www.clcillinois.edu/",
    "www.marin.edu/",
    "www.collegeofsanmateo.edu/",
    "www.csmd.edu/",
    "www.albemarle.edu/",
    "www.canyons.edu/",
    "www.collegeofthedesert.edu/",
    "https://cmn.edu/",
    "https://www.redwoods.edu/",
    "https://www.cos.edu/",
    "www.siskiyous.edu/",
    "https://cwi.edu/",
    "www.collins-cc.edu/",
    "www.cncc.edu/",
    "https://www.gocolumbia.edu/",
    "www.cgcc.edu/",
    "https://www.columbiastate.edu/",
    "https://www.sunycgcc.edu/",
    "https://www.cscc.edu/",
    "www.columbustech.edu/",
    "https://prami-fajardo.wixsite.com/admin",
    "https://www.ccac.edu/",
    "https://www.ccaurora.edu/",
    "www.ccbcmd.edu/",
    "https://www.ccbc.edu/",
    "www.ccp.edu/",
    "www.ccri.edu/",
    "www.ccv.edu/",
    "www.compton.edu/",
    "https://ctstate.edu/",
    "https://ctstate.edu/gateway",
    "https://ctstate.edu/housatonic",
    "https://ctstate.edu/",
    "www.tunxis.edu/",
    "connorsstate.edu/",
    "https://www.contracosta.edu/",
    "www.colin.edu/",
    "www.cmccd.edu/",
    "www.cccua.edu/",
    "https://www.crc.losrios.edu/",
    "www.ccm.edu/",
    "www.cowley.edu/",
    "www.craftonhills.edu/",
    "https://cravencc.edu/",
    "www.crowder.edu/",
    "ctaero.cttech.org/",
    "https://www.cuesta.edu/",
    "www.bmcc.cuny.edu/",
    "www.bcc.cuny.edu/",
    "www.hostos.cuny.edu/",
    "www.kbcc.cuny.edu/",
    "www.lagcc.cuny.edu/",
    "www.qcc.cuny.edu/",
    "https://www.guttman.cuny.edu/",
    "www.tri-c.edu/",
    "https://www.cuyamaca.edu/",
    "www.dakotacollege.edu/",
    "www.dctc.edu/",
    "www.dacc.edu/",
    "https://www.danville.edu/",
    "www.davidsondavie.edu/",
    "www.dawson.edu/",
    "https://www.deanza.edu/",
    "www.dccc.edu/",
    "https://www.dcc.edu/",
    "https://www.delta.edu/",
    "www.denmarktech.edu/",
    "https://www.dmacc.edu/",
    "https://www.dvc.edu/",
    "https://dc3.edu/",
    "www.das.edu/",
    "www.durhamtech.edu/",
    "https://www.sunydutchess.edu/",
    "www.dscc.edu/",
    "https://www.eacc.edu/",
    "www.eastcentral.edu/",
    "https://www.eccc.edu/",
    "www.elac.edu/",
    "www.eastms.edu/",
    "www.eac.edu/",
    "www.egcc.edu/",
    "www.eicc.edu/",
    "https://www.emcc.edu/",
    "www.ruidoso.enmu.edu/",
    "www.roswell.enmu.edu/",
    "www.eosc.edu/",
    "www.es.vccs.edu/",
    "www.easternwv.edu/",
    "https://ewc.wy.edu/",
    "www.edgecombe.edu/",
    "www.edisonohio.edu/",
    "www.elcamino.edu/",
    "www.epcc.edu/",
    "www.elgin.edu/",
    "https://elizabethtown.kctcs.edu/",
    "https://ecc.iavalley.edu/",
    "www.escc.edu/",
    "www.ecc.edu/",
    "www.hillsboroughschools.org/erwin",
    "escuelatroqueleria.jimdo.com/",
    "www.essex.edu/",
    "www.estrellamountain.edu/",
    "https://www.evc.edu/",
    "https://www.faytechcc.edu/",
    "www.flcc.edu/",
    "flaglertech.edu/",
    "www.fvcc.edu/",
    "www.fletcher.edu/",
    "www.fhtc.edu/",
    "https://www.fdtc.edu/",
    "https://www.flc.losrios.edu/",
    "https://www.forsythtech.edu/",
    "www.fortmyerstech.edu/",
    "www.fpcc.edu/",
    "www.fortscott.edu/",
    "https://www.fvtc.edu/",
    "www.fpctx.edu/",
    "mtec.pasco.k12.fl.us/",
    "fetc.edu/",
    "https://www.frederick.edu/",
    "www.fresnocitycollege.edu/",
    "https://www.iecc.edu/fcc",
    "www.fullcoll.edu/",
    "www.fmcc.edu/",
    "www.gadsdenstate.edu/",
    "www.gcccks.edu/",
    "www.garrettcollege.edu/index.php",
    "www.gaston.edu/",
    "https://gateway.kctcs.edu/index.aspx",
    "https://www.gtc.edu/",
    "https://www.gavilan.edu/",
    "https://www.genesee.edu/",
    "www.wallace.edu/",
    "https://www.wallacestate.edu/",
    "https://www.wccs.edu/",
    "www.georgestonecollege.edu/",
    "www.gntc.edu/",
    "www.gptc.edu/",
    "perimeter.gsu.edu/",
    "www.germanna.edu/",
    "www.glenoaks.edu/",
    "https://www.glendale.edu/",
    "gogebic.edu/",
    "www.goldenwestcollege.edu/",
    "www.gctech.edu/",
    "www.gradyhealth.org/",
    "https://www.grcc.edu/",
    "https://www.greatbay.edu/",
    "https://www.gfcmsu.edu/",
    "www.gcc.mass.edu/",
    "https://www.grossmont.edu/",
    "www.gtcc.edu/",
    "https://www.gwinnetttech.edu/",
    "www.trenholmstate.edu/",
    "www.hillsboroughschools.org/Brewster",
    "https://www.hagerstowncc.edu/",
    "www.halifaxcc.edu/",
    "www.harford.edu/",
    "www.hacc.edu/",
    "www.hartnell.edu/",
    "www.hawaii.hawaii.edu/",
    "www.hawkeyecollege.edu/",
    "https://www.haywood.edu/",
    "https://hazard.kctcs.edu/",
    "https://www.heartland.edu/",
    "https://www.helenacollege.edu/",
    "https://henderson.kctcs.edu/",
    "www.hennepintech.edu/",
    "www.herkimer.edu/",
    "www.highlandcc.edu/",
    "www.highland.edu/",
    "https://www.mtech.edu/",
    "https://www.hillcollege.edu/",
    "www.hindscc.edu/",
    "www.hocking.edu/",
    "www.holmescc.edu/",
    "www.hcc.edu/",
    "https://www.honolulu.hawaii.edu/",
    "https://hopkinsville.kctcs.edu/index.aspx",
    "www.hgtc.edu/",
    "https://www.howardcollege.edu/",
    "www.howardcc.edu/",
    "www.hccc.edu/",
    "www.hvcc.edu/",
    "www.hutchcc.edu/",
    "icc.edu/",
    "https://www.ivcc.edu/",
    "www.itech.edu/",
    "www.imperial.edu/",
    "www.indycc.edu/",
    "www.ictech.edu/",
    "https://www.indianhills.edu/",
    "www.de.gov/itec-2/",
    "itec.pr/ITPR-Joomla/",
    "https://instituto-tecnologico-de-puerto-rico-1.jimdosite.com/",
    "https://www.inverhills.edu/",
    "www.iowacentral.edu/",
    "www.iowalakes.edu/",
    "www.iwcc.edu/",
    "https://www.ivc.edu/",
    "https://www.isothermal.edu/",
    "www.iccms.edu/",
    "www.ivytech.edu/",
    "www.reynolds.edu/",
    "https://drakestate.edu/",
    "www.jscc.edu/",
    "www.jamessprunt.edu/",
    "https://www.sunyjcc.edu/",
    "https://www.jeffco.edu/",
    "https://jefferson.kctcs.edu/",
    "https://www.sunyjefferson.edu/",
    "www.jeffersonstate.edu/",
    "https://www.jalc.edu/",
    "https://calhoun.edu/",
    "www.jwcc.edu/",
    "www.jccc.edu/",
    "www.johnstoncc.edu/",
    "www.jjc.edu/",
    "www.jcjc.edu/",
    "https://www.kvcc.edu/",
    "https://www.kcc.edu/",
    "www.kckcc.edu/",
    "https://www.kapiolani.hawaii.edu/",
    "https://www.kaskaskia.edu/",
    "https://www.kauai.hawaii.edu/",
    "www.kellogg.edu/",
    "www.kvcc.me.edu/",
    "www.kbocc.edu/",
    "https://www.kilgore.edu/",
    "www.kirkwood.edu/",
    "https://www.kirtland.edu/",
    "www.kish.edu/",
    "https://www.klamathcc.edu/",
    "www.labette.edu/",
    "www.lakeareatech.edu/",
    "www.lakelandcollege.edu/",
    "https://www.lakemichigancollege.edu/",
    "www.lrsc.edu/",
    "www.lsc.edu/",
    "www.ltcc.edu/",
    "www.lakelandcc.edu/",
    "www.lrcc.edu/",
    "gotoltc.edu/",
    "https://www.lamarcc.edu/",
    "https://www.lit.edu/",
    "https://www.lsco.edu/",
    "www.lamarpa.edu/",
    "www.lancasterctc.edu/",
    "https://www.lanecc.edu/",
    "laney.edu/",
    "https://www.laniertech.edu/",
    "https://www.lcc.edu/",
    "www.laspositascollege.edu/",
    "www.lassencollege.edu/",
    "https://www.laurelridge.edu/",
    "www.lawsonstate.edu/",
    "www.lee.edu/",
    "www.lltc.edu/",
    "www.leeward.hawaii.edu/",
    "www.lccc.edu/",
    "https://www.westhillscollege.com/lemoore/",
    "https://www.lenoircc.edu/",
    "www.lc.edu/",
    "www.llcc.edu/",
    "https://www.iecc.edu/ltc",
    "www.lindseyhopkins.edu/",
    "https://www.linnbenton.edu/",
    "www.lbhc.edu/",
    "https://www.littlepriest.edu/",
    "www.lbcc.edu/",
    "www.lacitycollege.edu/",
    "https://dhs.lacounty.gov/college-of-nursing-and-allied-health/",
    "https://www.lahc.edu/",
    "https://www.lamission.edu/",
    "www.lapc.edu/",
    "https://www.lasc.edu/",
    "www.lattc.edu/",
    "www.lavc.edu/",
    "https://www.losmedanos.edu/",
    "https://www.ladelta.edu/",
    "https://www.lsue.edu/",
    "www.luna.edu/",
    "https://www.lbwcc.edu/",
    "www.luzerne.edu/",
    "www.macomb.edu/",
    "https://www.maderacollege.edu/",
    "www.madisonadultcc.org/",
    "https://madisonville.kctcs.edu/",
    "www.manateetech.edu/",
    "www.manchestercc.edu/",
    "www.mccnh.edu/",
    "https://manhattantech.edu/",
    "www.marionmilitary.edu/",
    "www.mariontc.edu/",
    "https://mcc.iavalley.edu/",
    "www.martincc.edu/",
    "https://www.massbay.edu/",
    "https://www.massasoit.edu/",
    "https://www.mayland.edu/",
    "https://maysville.kctcs.edu/",
    "https://www.mcdowelltech.edu/",
    "www.mchenry.edu/",
    "www.mclennan.edu/",
    "www.mendocino.edu/",
    "www.mccd.edu/",
    "www.mccc.edu/",
    "https://mercercountyschools.sites.thrillshare.com/o/mctec",
    "www.meridiancc.edu/",
    "https://www.meridiantech.edu/",
    "www.merritt.edu/",
    "www.mesacc.edu/",
    "www.mesalands.edu/",
    "https://www.metrotech.edu/",
    "https://www.mccneb.edu/",
    "www.mcckc.edu/",
    "https://miamilakes.edu/",
    "www.midmich.edu/",
    "www.mpcc.edu/",
    "https://www.mstc.edu/",
    "www.middlesexcollege.edu/",
    "https://www.middlesex.mass.edu/",
    "www.mxcc.edu/",
    "https://www.midlandstech.edu/",
    "www.milescc.edu/",
    "https://www.matc.edu/",
    "https://mineralarea.edu/",
    "www.minneapolis.edu/",
    "https://minnesotanorth.edu/",
    "www.southeastmn.edu/",
    "www.minnesota.edu/",
    "www.mnwest.edu/",
    "www.missioncollege.edu/",
    "https://www.msdelta.edu/",
    "https://www.mgccc.edu/",
    "wp.missouristate.edu/",
    "https://www.mitchellcc.edu/",
    "https://mitchelltech.edu/",
    "www.macc.edu/",
    "https://www.mohave.edu/",
    "www.mvcc.edu/",
    "www.monroecc.edu/",
    "www.monroeccc.edu/",
    "www.montcalm.edu/",
    "www.mpc.edu/",
    "www.montgomerycollege.edu/",
    "www.montgomery.edu/",
    "www.mc3.edu/",
    "https://www.mntc.edu/",
    "www.moorparkcollege.edu/index.shtml",
    "www.morainepark.edu/",
    "www.morainevalley.edu/",
    "www.mvc.edu/",
    "www.morton.edu/",
    "www.mscc.edu/",
    "https://www.mcc.edu/",
    "mwcc.edu/",
    "www.mecc.edu/",
    "www.mgcc.edu/",
    "www.mctc.edu/",
    "www.mtsac.edu/",
    "www.msjc.edu/",
    "https://www.mscok.edu/",
    "www.muskegoncc.edu/",
    "https://www.napavalley.edu/",
    "https://www.nashcc.edu/",
    "nashuacc.edu/",
    "https://www.nscc.edu/",
    "www.ncc.edu/",
    "www.np.edu/",
    "https://nv.edu/",
    "https://ncta.unl.edu/",
    "www.neosho.edu/",
    "www.nmjc.edu/",
    "https://www.nmmi.edu/",
    "alamogordo.nmsu.edu/",
    "dacc.nmsu.edu/",
    "grants.nmsu.edu/",
    "https://www.newriver.edu/",
    "www.nr.edu/",
    "https://www.nhti.edu/",
    "www.niagaracc.suny.edu/",
    "https://www.nicoletcollege.edu/",
    "www.norcocollege.edu/Pages/index.aspx",
    "www.normandale.edu/",
    "www.northark.edu/",
    "www.ncktc.edu/",
    "www.ncmich.edu/",
    "www.ncmissouri.edu/",
    "https://www.nctc.edu/",
    "www.nccc.edu/",
    "https://www.ndscs.edu/",
    "https://northgatech.edu/",
    "https://www.nhcc.edu/",
    "https://www.nic.edu/",
    "www.niacc.edu/",
    "www.northshore.edu/",
    "www.northampton.edu/",
    "www.ntc.edu/",
    "https://www.nacc.edu/",
    "https://northeast.edu/",
    "https://www.nicc.edu/",
    "www.alamo.edu/nlc",
    "https://www.nemcc.edu/",
    "https://www.northeaststate.edu/",
    "www.ntcc.edu/",
    "https://www.nwtc.edu/",
    "www.njc.edu/",
    "www.neo.edu/",
    "www.netc.edu/",
    "www.necc.mass.edu/",
    "www.nmcc.edu/",
    "www.noc.edu/",
    "https://regionalcollegepa.org/",
    "https://www.nvcc.edu/",
    "https://www.sheridan.edu/",
    "www.northlandcollege.edu/",
    "www.npc.edu/",
    "northshorecollege.edu/",
    "www.nwacc.edu/",
    "www.nwicc.edu/",
    "www.nwktc.edu/",
    "www.nltcc.edu/",
    "www.northwestms.edu/",
    "https://www.nwscc.edu/",
    "https://northweststate.edu/",
    "https://www.ntcmn.edu/",
    "alamo.edu/nvc/",
    "www.nwcc.commnet.edu/",
    "https://www.northwoodtech.edu/",
    "www.nunez.edu/",
    "https://www.oaklandcc.edu/",
    "www.oakton.edu/",
    "www.ocean.edu/",
    "www.oftc.edu/",
    "www.ogeecheetech.edu/",
    "ati.osu.edu/",
    "www.ohlone.edu/",
    "www.occc.edu/",
    "https://www.iecc.edu/occ",
    "www.sunyocc.edu/",
    "orangecoastcollege.edu/",
    "https://sunyorange.edu/",
    "https://www.orangetechcollege.net/campuses/east_campus",
    "www.orangetechcollege.net/",
    "https://www.orangetechcollege.net/campuses/west_campus",
    "www.octech.edu/",
    "www.oregoncoastcc.org/",
    "www.otero.edu/",
    "https://www.owens.edu/",
    "https://owensboro.kctcs.edu/",
    "www.oxnardcollege.edu/",
    "https://www.ozarka.edu/",
    "palau.edu/",
    "alamo.edu/pac/",
    "https://www.paloverde.edu/",
    "www2.palomar.edu/",
    "www.pamlicocc.edu/",
    "www.panola.edu/",
    "www.parisjc.edu/",
    "https://www.parkland.edu/",
    "pasadena.edu/",
    "https://web.pccc.edu/",
    "www.patrickhenry.edu/",
    "www.pdc.edu/",
    "www.prcc.edu/",
    "www.pstcc.edu/",
    "www.pennhighlands.edu/",
    "www.pccua.edu/",
    "www.phoenixcollege.edu/",
    "www.pickenstech.org/",
    "www.piedmontcc.edu/",
    "https://www.ptc.edu/",
    "www.pvcc.edu/",
    "https://www.pierpont.edu/",
    "www.pima.edu/",
    "www.pine.edu/",
    "www.myptc.edu/",
    "www.myptc.edu/",
    "https://pittcc.edu/",
    "https://www.portervillecollege.edu/",
    "www.pcc.edu/",
    "prairiestate.edu/",
    "www.prattcc.edu/",
    "https://www.pgcc.edu/",
    "https://qvcc.edu/",
    "www.qcc.edu/",
    "www.locklintech.com/",
    "https://www.randolph.edu/",
    "https://www.rangercollege.edu/",
    "www.rappahannock.edu/",
    "https://www.raritanval.edu/",
    "https://www.racc.edu/",
    "www.rlnc.education/",
    "www.redlandscc.edu/",
    "www.reedleycollege.edu/",
    "www.rstc.edu/",
    "www.rlc.edu/",
    "www.rbc.edu/",
    "https://www.richland.edu/",
    "https://www.richmondcc.edu/",
    "www.ridgewater.edu/",
    "www.rpcc.edu/",
    "https://www.rivervalley.edu/",
    "https://www.riverland.edu/",
    "rtc.suwannee.k12.fl.us/",
    "www.rcc.edu/",
    "www.roanestate.edu/",
    "www.rjtcwv.com/",
    "www.roanokechowan.edu/",
    "www.robertmorgantech.net/",
    "www.robeson.edu/",
    "www.rctc.edu/",
    "www.rockvalleycollege.edu/",
    "https://www.rockinghamcc.edu/",
    "www.sunyrockland.edu/",
    "www.roguecc.edu/",
    "https://www.rose.edu/",
    "www.rcbc.edu/",
    "https://rcsj.edu/",
    "rcsj.edu/",
    "https://www.rccc.edu/",
    "www.rcc.mass.edu/",
    "https://www.scc.losrios.edu/",
    "https://www.saddleback.edu/",
    "www.sagchip.edu/",
    "https://www.saintpaul.edu/",
    "https://www.salemcc.edu/",
    "www.salinatech.edu/",
    "www.slcc.edu/",
    "www.sampsoncc.edu/",
    "www.valleycollege.edu/",
    "www.sdcity.edu/",
    "www.sdmiramar.edu/",
    "www.deltacollege.edu/",
    "www.sjcc.edu/",
    "www.sanjuancollege.edu/",
    "https://www.sandhills.edu/",
    "www.sbcc.edu/",
    "https://www.sfcc.edu/",
    "www.santarosa.edu/",
    "www.sccollege.edu/SitePages/Home.aspx",
    "www.svcc.edu/",
    "www.savannahtech.edu/",
    "sunysccc.edu/",
    "www.scottsdalecc.edu/",
    "www.sscok.edu/",
    "sccc.edu/",
    "https://shawneecc.edu/",
    "www.sheltonstate.edu/",
    "www.sheridantechnicalcollege.edu/",
    "www.shoreline.edu/",
    "https://www.sierracollege.edu/",
    "www.snead.edu/",
    "https://somerset.kctcs.edu/",
    "www.southark.edu/",
    "southcentral.edu/",
    "www.southgatech.edu/",
    "https://www.solacc.edu/",
    "www.southmountaincc.edu/",
    "https://www.spcc.edu/",
    "www.southplainscollege.edu/",
    "www.spscc.edu/",
    "https://www.ssc.edu/",
    "https://southcentral.kctcs.edu/",
    "https://www.seark.edu/",
    "www.southeast.edu/",
    "https://southeast.kctcs.edu/",
    "senmc.edu/",
    "www.southeasttech.edu/",
    "www.sccnc.edu/",
    "www.scciowa.edu/",
    "www.sic.edu/",
    "www.southeasterntech.edu/",
    "www.sautech.edu/",
    "www.sctech.edu/",
    "https://www.smccme.edu/",
    "southernregional.edu/",
    "https://www.sscc.edu/",
    "www.suscc.edu/",
    "www.susla.edu/",
    "https://www.southernwv.edu/",
    "https://www.southside.edu/",
    "https://howardcollege.edu/swcd/",
    "https://www.smcc.edu/",
    "www.southwest.tn.edu/",
    "https://www.swtjc.edu/",
    "sw.edu/",
    "https://www.swtc.edu/",
    "https://www.swccd.edu/",
    "www.swcciowa.edu/",
    "https://www.southwesterncc.edu/",
    "https://www.swic.edu/",
    "www.sipi.edu/",
    "www.swmich.edu/",
    "www.socc.edu/",
    "www.sowela.edu/",
    "https://www.sccsc.edu/",
    "www.src.edu/",
    "www.stcc.edu/",
    "www.stchas.edu/",
    "www.sc4.edu/",
    "www.sctcc.edu/",
    "www.alamo.edu/spc/",
    "www.stanly.edu/",
    "www.starkstate.edu/",
    "https://www.sfccmo.edu/",
    "https://www.statetechmo.edu/",
    "ssamt.cttech.org/",
    "https://www.sunysuffolk.edu/",
    "https://www.sunysullivan.edu/",
    "www.sarasotacountyschools.net/suncoasttechnicalcollege",
    "www.sunyacc.edu/",
    "www.sunybroome.edu/",
    "https://www.corning-cc.edu/",
    "www.sunywcc.edu/",
    "https://surry.edu/",
    "www.sussex.edu/",
    "www.taftcollege.edu/",
    "www.tccd.edu/",
    "tcl.edu/",
    "www.templejc.edu/",
    "www.tcatnashville.edu/",
    "https://www.tcatnorthwest.edu/",
    "www.tcatathens.edu/",
    "www.tcatcovington.edu/",
    "www.tcatcrossville.edu/",
    "www.tcatcrump.edu/",
    "https://www.tcatdickson.edu/",
    "www.tcatelizabethton.edu/",
    "www.tcatharriman.edu/",
    "www.tcathartsville.edu/",
    "https://www.tcathenrycarroll.edu/",
    "www.tcathohenwald.edu/",
    "https://www.tcatjacksboro.edu/",
    "www.tcatjackson.edu/",
    "https://www.tcatknoxville.edu/",
    "www.tcatlivingston.edu/",
    "www.tcatmckenzie.edu/",
    "tcatmcminnville.edu/",
    "www.tcatmemphis.edu/",
    "www.tcatmorristown.edu/",
    "www.tcatmurfreesboro.edu/",
    "https://tcatoneida.edu/",
    "www.tcatpulaski.edu/",
    "www.tcatshelbyville.edu/",
    "www.terra.edu/",
    "https://www.texarkanacollege.edu/",
    "www.tsc.edu/",
    "www.tstc.edu/",
    "stevenscollege.edu/",
    "https://trcc.edu/",
    "https://www.threerivers.edu/",
    "www.tcc.edu/",
    "tillamookbaycc.edu/",
    "www.tocc.edu/",
    "www.tps.org/",
    "www.tompkinscortland.edu/",
    "https://www.tvcc.cc/",
    "www.tri-communityadulted.org/",
    "https://www.tricountycc.edu/",
    "https://www.tctc.edu/",
    "https://www.tridenttech.edu/",
    "www.triton.edu/",
    "www.tulsacc.edu/",
    "https://tulsatech.edu/",
    "https://www.ucc.edu/",
    "https://www.sunyulster.edu/",
    "https://www.umpqua.edu/",
    "https://wayne.uakron.edu/",
    "https://www.uarichmountain.edu/",
    "www.uaccb.edu/",
    "www.uaccm.edu/",
    "www.uaht.edu/",
    "uaptc.edu/",
    "www.gallup.unm.edu/",
    "losalamos.unm.edu/",
    "dacc.nmsu.edu/",
    "grants.nmsu.edu/",
    "www.titusville.pitt.edu/home",
    "www.sc.edu/about/system_and_campuses/lancaster/index.php",
    "sc.edu/about/system_and_campuses/salkehatchie/index.php",
    "www.sc.edu/about/system_and_campuses/sumter/index.php",
    "www.sc.edu/about/system_and_campuses/union/index.php",
    "www.vgcc.edu/",
    "www.venturacollege.edu/",
    "www.vernoncollege.edu/",
    "www.vvc.edu/",
    "www.victoriacollege.edu/",
    "www.vhcc.edu/",
    "https://vpcc.edu/",
    "virginiawestern.edu/",
    "www.volstate.edu/",
    "https://www.iecc.edu/wvc",
    "www.waketech.edu/",
    "www.ws.edu/",
    "www.warren.edu/",
    "www.wccc.me.edu/",
    "www.wccnet.edu/",
    "https://www.waubonsee.edu/",
    "https://www.wctc.edu/",
    "www.waynecc.edu/",
    "www.wcccd.edu/",
    "https://www.westgatech.edu/",
    "https://westkentucky.kctcs.edu/",
    "https://www.westshore.edu/",
    "www.westvalley.edu/",
    "www.wvncc.edu/",
    "https://www.wdt.edu/",
    "https://www.witcc.edu/",
    "https://west-mec.edu/findyourhappy",
    "www.wncc.edu/",
    "www.wosc.edu/",
    "https://www.wpcc.edu/",
    "www.wilsontech.org/",
    "https://www.westerntc.edu/",
    "www.wtc.edu/",
    "https://www.westmoreland.edu/",
    "https://www.wcjc.edu/",
    "www.wmcc.edu/",
    "www.wsutech.edu/",
    "www.wilkescc.edu/",
    "https://www.harpercollege.edu/index.php",
    "www.mcfattertechnicalcollege.edu/",
    "https://www.wiltech.edu/",
    "https://willistonstate.edu/",
    "www.wilsoncc.edu/",
    "https://windward.hawaii.edu/",
    "https://www.wiregrass.edu/",
    "www.wtcollege.org/",
    "https://wcc.yccd.edu/",
    "www.worwic.edu/",
    "www.wcc.vccs.edu/",
    "https://www.yccc.edu/",
    "www.yorktech.edu/",
    "https://yc.yccd.edu/"
]


# 2. Helper function: Perform a Google Custom Search API request
def google_search(query):
    """
    Returns the JSON response from the Custom Search API or an empty dict if error.
    """
    api_key = st.secrets["GOOGLE_API_KEY"]
    cse_id = st.secrets["GOOGLE_CSE_ID"]
    url = "https://www.googleapis.com/customsearch/v1"
    params = {
        "key": api_key,
        "cx": cse_id,
        "q": query,
    }
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return response.json()
    else:
        st.error(f"Google API error: {response.status_code}")
        return {}

# 3. Helper function: Extract a years range (e.g. "2025-2030") from a text snippet
def extract_years(text):
    """
    Look for a pattern like 2025-2030 or 2025 - 2030
    """
    pattern = r"\b(20\d{2}\s*-\s*20\d{2})\b"
    matches = re.findall(pattern, text)
    return matches[0] if matches else ""

# 4. Helper function: Attempt to find an enrollment number from a snippet
def extract_enrollment(snippet):
    """
    Attempt to match a large integer or an integer with commas, e.g. 15,000 or 15000.
    """
    match = re.search(r"(\d{1,3}(,\d{3})+|\d{4,})", snippet)
    return match.group(1) if match else ""

def search_enrollment(domain):
    """
    Query the domain for 'enrollment' and return the first matched number from the snippet.
    """
    enrollment_query = f'site:{domain} enrollment'
    search_results = google_search(enrollment_query)
    if "items" not in search_results:
        return ""
    for item in search_results["items"]:
        snippet = item.get("snippet", "")
        found = extract_enrollment(snippet)
        if found:
            return found
    return ""

def main():
    st.title("Community College Strategic Plan Search")
    st.write(
        "This app runs a Google Custom Search query against a fixed list of community-college URLs. "
        "It looks for the phrase **'strategic plan'**, extracts any referenced **years** (e.g. 2025-2030), "
        "and attempts to find **enrollment** numbers from the same domain."
    )

    if st.button("Run Search"):
        results_data = []
        
        # Because the list is long, you might want to limit for testing:
        # for college_url in COMMUNITY_COLLEGE_URLS[:10]:
        for college_url in COMMUNITY_COLLEGE_URLS:
            # Parse out the domain
            parsed = urlparse(college_url if college_url.startswith("http") else "http://" + college_url)
            domain = parsed.netloc.lower()
            if not domain:
                # If the URL is malformed, skip
                continue
            
            # Primary query to find "strategic plan"
            plan_query = f'site:{domain} "strategic plan"'
            plan_results = google_search(plan_query)

            snippet_text = ""
            years_range = ""
            if "items" in plan_results:
                # Just take the first item for demonstration
                first_item = plan_results["items"][0]
                snippet_text = first_item.get("snippet", "")
                # Attempt to extract a years range
                years_range = extract_years(snippet_text)
            
            # Secondary query to find enrollment
            enrollment_size = ""
            if snippet_text:
                enrollment_size = search_enrollment(domain)

            results_data.append({
                "URL": college_url,
                "Enrollment Size": enrollment_size,
                "Strategic Plan Text": snippet_text,
                "Years Referenced": years_range,
            })
        
        # Create a DataFrame
        df = pd.DataFrame(results_data)
        st.subheader("Search Results")
        st.dataframe(df)

    else:
        st.info("Click the 'Run Search' button to begin.")

if __name__ == "__main__":
    main()
